using System;
using System.Collections.Generic;
using static DecorationsModConfigurator.TechTypes;

namespace DecorationsModConfigurator
{
    public static class TechTypeExtensions
    {
        static TechTypeExtensions()
        {
            Array values = Enum.GetValues(typeof(TechType));
            int length = values.Length;
            TechTypeExtensions.stringsNormal = new Dictionary<TechType, string>(length, TechTypeExtensions.sTechTypeComparer);
            TechTypeExtensions.stringsLowercase = new Dictionary<TechType, string>(length, TechTypeExtensions.sTechTypeComparer);
            TechTypeExtensions.techTypesNormal = new Dictionary<string, TechType>(length);
            TechTypeExtensions.techTypesIgnoreCase = new Dictionary<string, TechType>(length, StringComparer.InvariantCultureIgnoreCase);
            TechTypeExtensions.techTypeKeys = new Dictionary<TechType, string>(length, TechTypeExtensions.sTechTypeComparer);
            TechTypeExtensions.keyTechTypes = new Dictionary<string, TechType>(length);
            for (int i = 0; i < length; i++)
            {
                TechType techType = (TechType)values.GetValue(i);
                string text = techType.ToString();
                if (!TechTypeExtensions.stringsNormal.ContainsKey(techType))
                {
                    TechTypeExtensions.stringsNormal[techType] = text;
                    TechTypeExtensions.stringsLowercase[techType] = text.ToLower();
                }
                if (!TechTypeExtensions.techTypesNormal.ContainsKey(text))
                    TechTypeExtensions.techTypesNormal[text] = techType;
                if (!TechTypeExtensions.techTypesIgnoreCase.ContainsKey(text))
                    TechTypeExtensions.techTypesIgnoreCase[text] = techType;
                int num = (int)techType;
                string text2 = num.ToString();
                TechTypeExtensions.techTypeKeys.Add(techType, text2);
                TechTypeExtensions.keyTechTypes.Add(text2, techType);
            }
        }

        public static string AsString(this TechType techType, bool lowercase = false)
        {
            string result;
            if (lowercase)
            {
                if (TechTypeExtensions.stringsLowercase.TryGetValue(techType, out result))
                    return result;
            }
            else if (TechTypeExtensions.stringsNormal.TryGetValue(techType, out result))
                return result;
            int num = (int)techType;
            return num.ToString();
        }

        public static bool FromString(string str, out TechType techType, bool ignoreCase)
        {
            if (ignoreCase)
                return TechTypeExtensions.techTypesIgnoreCase.TryGetValue(str, out techType);
            return TechTypeExtensions.techTypesNormal.TryGetValue(str, out techType);
        }

        public static string EncodeKey(this TechType techType)
        {
            string result;
            if (TechTypeExtensions.techTypeKeys.TryGetValue(techType, out result))
                return result;
            return null;
        }

        public static TechType DecodeKey(this string key)
        {
            TechType result;
            if (TechTypeExtensions.keyTechTypes.TryGetValue(key, out result))
                return result;
            return TechType.None;
        }

        public static readonly TechTypeExtensions.TechTypeComparer sTechTypeComparer = new TechTypeExtensions.TechTypeComparer();

        private static Dictionary<TechType, string> stringsNormal;
        private static Dictionary<TechType, string> stringsLowercase;
        private static Dictionary<string, TechType> techTypesNormal;
        private static Dictionary<string, TechType> techTypesIgnoreCase;
        private static Dictionary<TechType, string> techTypeKeys;
        private static Dictionary<string, TechType> keyTechTypes;

        public class TechTypeComparer : IEqualityComparer<TechType>
        {
            public bool Equals(TechType x, TechType y)
            {
                int num = (int)x;
                return num.Equals((int)y);
            }

            public int GetHashCode(TechType techType)
            {
                return (int)techType;
            }
        }
    }

    public static class TechTypes
    {
        public enum TechType
        {
            None,
            Quartz,
            ScrapMetal,
            FiberMesh,
            LimestoneChunk,
            CalciteOld,
            DolomiteOld,
            Copper,
            Lead,
            Salt,
            FlintOld,
            EmeryOld,
            MercuryOre,
            CalciumChunk,
            Placeholder,
            Glass,
            Titanium,
            Silicone,
            CarbonOld,
            EthanolOld,
            EthyleneOld,
            Gold,
            Magnesium,
            Sulphur,
            HydrogenOld,
            Lodestone,
            SandLoot,
            Bleach,
            Silver,
            BatteryAcidOld,
            TitaniumIngot,
            SandstoneChunk,
            CopperWire,
            WiringKit,
            AdvancedWiringKit,
            CrashPowder,
            Diamond,
            BasaltChunk,
            ShaleChunk,
            ObsidianChunk,
            Lithium,
            PlasteelIngot,
            EnameledGlass,
            PowerCell,
            ComputerChip,
            Fiber,
            Enamel,
            AcidOld,
            VesselOld,
            CombustibleOld,
            OpalGem,
            Uranium,
            AluminumOxide,
            HydrochloricAcid,
            Magnetite,
            AminoAcids,
            Polyaniline,
            AramidFibers,
            Graphene,
            Aerogel,
            Nanowires,
            Benzene,
            Lubricant,
            UraniniteCrystal,
            ReactorRod,
            DepletedReactorRod,
            PrecursorIonCrystal,
            PrecursorIonCrystalMatrix,
            Kyanite,
            Nickel,
            DrillableSalt,
            DrillableQuartz,
            DrillableCopper,
            DrillableTitanium,
            DrillableLead,
            DrillableSilver,
            DrillableDiamond,
            DrillableGold,
            DrillableMagnetite,
            DrillableLithium,
            DrillableMercury,
            DrillableUranium,
            DrillableAluminiumOxide,
            DrillableNickel,
            DrillableSulphur,
            DrillableKyanite,
            DiveSuit = 500,
            ShipComputerOld,
            Fins,
            Tank,
            Battery,
            Knife,
            Drill,
            Flashlight,
            Beacon,
            Builder,
            PDA,
            EscapePod,
            Compass,
            AirBladder,
            Terraformer,
            Pipe,
            Thermometer,
            DiveReel,
            Rebreather,
            RadiationSuit,
            RadiationHelmet,
            RadiationGloves,
            ReinforcedDiveSuit,
            Scanner,
            FireExtinguisher,
            MapRoomHUDChip,
            PipeSurfaceFloater,
            CyclopsDecoy,
            DoubleTank,
            ReinforcedGloves,
            Welder = 750,
            Seaglide,
            Constructor,
            Transfuser,
            Flare,
            StasisRifle,
            BuildBot,
            PropulsionCannon,
            Gravsphere,
            SmallStorage,
            StasisSphere,
            LaserCutter,
            LEDLight,
            DiamondBlade = 800,
            HeatBlade,
            LithiumIonBattery,
            PlasteelTank,
            HighCapacityTank,
            UltraGlideFins,
            SwimChargeFins,
            RepulsionCannon,
            Stillsuit,
            PowerGlide,
            CompostCreepvine = 900,
            ProcessUranium,
            PrecursorIonEnergyBlueprint = 950,
            FabricatorBlueprintOld = 1000,
            ConstructorBlueprint,
            CyclopsBlueprint,
            FragmentAnalyzerBlueprintOld,
            LockerBlueprint,
            SpecialHullPlateBlueprintOld,
            BikemanHullPlateBlueprintOld,
            EatMyDictionHullPlateBlueprintOld,
            DevTestItemBlueprintOld,
            SeamothBlueprint,
            StasisRifleBlueprint,
            ExosuitBlueprint,
            TransfuserBlueprint,
            TerraformerBlueprint,
            ReinforceHullBlueprint,
            WorkbenchBlueprint,
            PropulsionCannonBlueprint,
            SpecimenAnalyzerBlueprint,
            BioreactorBlueprint,
            ThermalPlantBlueprint,
            NuclearReactorBlueprint,
            MoonpoolBlueprint,
            FiltrationMachineBlueprint,
            TechlightBlueprint,
            LEDLightBlueprint,
            CyclopsHullBlueprint,
            CyclopsBridgeBlueprint,
            CyclopsEngineBlueprint,
            CyclopsDockingBayBlueprint,
            SpotlightBlueprint,
            RadioBlueprint,
            StarshipCargoCrateBlueprint,
            StarshipCircuitBoxBlueprint,
            StarshipDeskBlueprint,
            StarshipChairBlueprint,
            StarshipMonitorBlueprint,
            SolarPanelBlueprint,
            PowerTransmitterBlueprint,
            BaseUpgradeConsoleBlueprint,
            BaseObservatoryBlueprint,
            BaseWaterParkBlueprint,
            PictureFrameBlueprint,
            BaseRoomBlueprint,
            BaseBulkheadBlueprint,
            SeaglideBlueprint,
            BatteryChargerBlueprint,
            PowerCellChargerBlueprint,
            FarmingTrayBlueprint,
            SignBlueprint,
            BenchBlueprint,
            PlanterPotBlueprint,
            PlanterBoxBlueprint,
            PlanterShelfBlueprint,
            AquariumBlueprint,
            ReinforcedDiveSuitBlueprint,
            RadiationSuitBlueprint,
            StillsuitBlueprint,
            ScannerRoomBlueprint,
            BasePlanterBlueprint,
            PlanterPot2Blueprint,
            PlanterPot3Blueprint,
            MedicalCabinetBlueprint,
            BaseMapRoomBlueprint,
            SeamothFragment = 1100,
            StasisRifleFragment,
            ExosuitFragment,
            TransfuserFragment,
            TerraformerFragment,
            ReinforceHullFragment,
            WorkbenchFragment,
            PropulsionCannonFragment,
            BioreactorFragment,
            ThermalPlantFragment,
            NuclearReactorFragment,
            MoonpoolFragment,
            BaseFiltrationMachineFragment,
            CyclopsHullFragment,
            CyclopsBridgeFragment,
            CyclopsEngineFragment,
            CyclopsDockingBayFragment,
            SeaglideFragment,
            ConstructorFragment,
            SolarPanelFragment,
            PowerTransmitterFragment,
            BaseUpgradeConsoleFragment,
            BaseObservatoryFragment,
            BaseWaterParkFragment,
            RadioFragment,
            BaseRoomFragment,
            BaseBulkheadFragment,
            BatteryChargerFragment,
            PowerCellChargerFragment,
            ScannerRoomFragment,
            SpecimenAnalyzerFragment,
            FarmingTrayFragment,
            SignFragment,
            PictureFrameFragment,
            BenchFragment,
            PlanterPotFragment,
            PlanterBoxFragment,
            PlanterShelfFragment,
            AquariumFragment,
            ReinforcedDiveSuitFragment,
            RadiationSuitFragment,
            StillsuitFragment,
            BuilderFragment,
            LEDLightFragment,
            TechlightFragment,
            SpotlightFragment,
            BaseMapRoomFragment,
            BaseBioReactorFragment,
            BaseNuclearReactorFragment,
            LaserCutterFragment,
            BeaconFragment,
            GravSphereFragment,
            SafeShallowsEgg = 1250,
            KelpForestEgg,
            GrassyPlateausEgg,
            GrandReefsEgg,
            MushroomForestEgg,
            KooshZoneEgg,
            TwistyBridgesEgg,
            LavaZoneEgg,
            StalkerEgg,
            ReefbackEgg,
            SpadefishEgg,
            RabbitrayEgg,
            MesmerEgg,
            JumperEgg,
            SandsharkEgg,
            JellyrayEgg,
            BonesharkEgg,
            CrabsnakeEgg,
            ShockerEgg,
            GasopodEgg,
            RabbitrayEggUndiscovered,
            JellyrayEggUndiscovered,
            StalkerEggUndiscovered,
            ReefbackEggUndiscovered,
            JumperEggUndiscovered,
            BonesharkEggUndiscovered,
            GasopodEggUndiscovered,
            MesmerEggUndiscovered,
            SandsharkEggUndiscovered,
            ShockerEggUndiscovered,
            GenericEgg,
            CrashEgg,
            CrashEggUndiscovered,
            CrabsquidEgg,
            CrabsquidEggUndiscovered,
            CutefishEgg,
            CutefishEggUndiscovered,
            LavaLizardEgg,
            LavaLizardEggUndiscovered,
            CrabsnakeEggUndiscovered,
            SpadefishEggUndiscovered,
            ReefbackShell = 1300,
            ReefbackTissue,
            ReefbackAdvancedStructure,
            ReefbackDNA = 1400,
            Workbench = 1500,
            HullReinforcementModule,
            Fabricator,
            Aquarium,
            Locker,
            Spotlight,
            DiveHatch,
            CurrentGenerator,
            FragmentAnalyzer,
            SpecialHullPlate,
            BikemanHullPlate,
            EatMyDictionHullPlate,
            DevTestItem,
            SpecimenAnalyzer,
            HullReinforcementModule2,
            HullReinforcementModule3,
            PowerUpgradeModule,
            SolarPanel,
            Sign,
            PowerTransmitter,
            Accumulator,
            Bioreactor,
            ThermalPlant,
            NuclearReactor,
            SmallLocker,
            Bench,
            PictureFrame,
            PlanterPot,
            PlanterBox,
            PlanterShelf,
            FarmingTray,
            FiltrationMachine,
            Techlight,
            Radio,
            PlanterPot2,
            PlanterPot3,
            MedicalCabinet,
            CyclopsHullModule1,
            CyclopsHullModule2,
            SingleWallShelf,
            WallShelves,
            Bed1,
            Bed2,
            NarrowBed,
            BatteryCharger,
            PowerCellCharger,
            Incubator,
            HatchingEnzymes,
            EnyzmeCloud,
            EnzymeCureBall,
            Centrifuge,
            CyclopsShieldModule,
            CyclopsSonarModule,
            CyclopsSeamothRepairModule,
            CyclopsDecoyModule,
            CyclopsFireSuppressionModule,
            CyclopsFabricator,
            CyclopsThermalReactorModule,
            CyclopsHullModule3,
            StarshipCargoCrate = 1800,
            StarshipCircuitBox,
            StarshipDesk,
            StarshipChair,
            StarshipMonitor,
            StarshipChair2,
            StarshipChair3,
            LuggageBag,
            ArcadeGorgetoy,
            LabEquipment1,
            LabEquipment2,
            LabEquipment3,
            CoffeeVendingMachine,
            BarTable,
            Cap1,
            Cap2,
            LabContainer,
            LabContainer2,
            LabContainer3,
            Trashcans,
            LabTrashcan,
            VendingMachine,
            LabCounter,
            StarshipSouvenir,
            PosterAurora,
            PosterExoSuit1,
            PosterExoSuit2,
            PosterKitty,
            ToyCar,
            Seamoth = 2000,
            Exosuit,
            CrashedShip,
            Cyclops,
            Audiolog,
            Signal,
            SeamothReinforcementModule = 2100,
            VehiclePowerUpgradeModule,
            SeamothSolarCharge,
            VehicleStorageModule,
            SeamothElectricalDefense,
            VehicleArmorPlating,
            LootSensorMetal,
            LootSensorLithium,
            LootSensorFragment,
            SeamothTorpedoModule,
            SeamothSonarModule,
            WhirlpoolTorpedo,
            VehicleHullModule1,
            VehicleHullModule2,
            VehicleHullModule3,
            ExosuitJetUpgradeModule,
            ExosuitDrillArmModule,
            ExosuitThermalReactorModule,
            ExosuitClawArmModule,
            GasTorpedo,
            ExosuitPropulsionArmModule,
            ExosuitGrapplingArmModule,
            ExosuitTorpedoArmModule,
            ExosuitDrillArmFragment,
            ExosuitPropulsionArmFragment,
            ExosuitGrapplingArmFragment,
            ExosuitTorpedoArmFragment,
            ExosuitClawArmFragment,
            ExoHullModule1,
            ExoHullModule2,
            MapRoomUpgradeScanRange = 2250,
            MapRoomUpgradeScanSpeed,
            Creepvine = 2500,
            HoleFish,
            Jumper,
            CreepvineSeedCluster,
            Peeper,
            Oculus,
            RabbitRay,
            GarryFish,
            Slime,
            Crash,
            Boomerang,
            LavaLarva,
            Stalker,
            Eyeye,
            Bloom,
            Bladderfish,
            Hoverfish,
            Jellyray,
            Reefback,
            Reginald,
            Spadefish,
            Grabcrab,
            Floater,
            Gasopod,
            Sandshark,
            Player,
            Bleeder,
            Rockgrub,
            CrashHome,
            CreepvinePiece,
            GasPod,
            Hoopfish,
            HoopfishSchool,
            RockPuncher,
            BoneShark,
            Mesmer,
            SeaTreader,
            SeaEmperor,
            Cutefish,
            Crabsnake,
            ReaperLeviathan,
            CaveCrawler,
            Skyray,
            Biter,
            SkyrayNonRoosting,
            Shocker,
            Spinefish,
            Shuttlebug,
            Blighter,
            Warper,
            CrabSquid,
            LavaLizard,
            SpineEel,
            SeaDragon,
            LavaBoomerang,
            LavaEyeye,
            SeaEmperorBaby,
            WarperSpawner,
            GhostRayBlue,
            GhostRayRed,
            ReefbackBaby,
            PrecursorDroid,
            GhostLeviathan,
            SeaEmperorLeviathan,
            SeaEmperorJuvenile,
            GhostLeviathanJuvenile,
            HoleFishAnalysis = 2700,
            PeeperAnalysis,
            BladderfishAnalysis,
            GarryFishAnalysis,
            HoverfishAnalysis,
            ReginaldAnalysis,
            SpadefishAnalysis,
            BoomerangAnalysis,
            EyeyeAnalysis,
            OculusAnalysis,
            HoopfishAnalysis,
            AnalysisTreeOld,
            SpinefishAnalysis,
            PlantPlaceholder = 3000,
            BallClusters,
            BarnacleSuckers,
            BlueBarnacle,
            BlueBarnacleCluster,
            BlueCoralTubes,
            RedGrass,
            GreenGrass,
            Mohawk,
            GreenReeds,
            JellyPlant,
            BlueJeweledDisk,
            GreenJeweledDisk,
            PurpleJeweledDisk,
            RedJeweledDisk,
            SmallKoosh,
            MediumKoosh,
            LargeKoosh,
            HugeKoosh,
            MembrainTree,
            PurpleFan,
            AcidMushroom,
            PurpleTentacle,
            RedSeaweed,
            CoralOldPlaceholder,
            CoralShellPlate,
            SmallFan,
            SmallFanCluster,
            BigCoralTubes,
            TreeMushroom,
            BlueCluster,
            BrownTubes,
            BloodGrass,
            HeatArea,
            BloodOil,
            WhiteMushroom,
            BloodRoot,
            BloodVine,
            PinkFlower,
            PinkMushroom,
            PurpleRattle,
            BulboTree,
            PurpleVasePlant,
            OrangeMushroom,
            FernPalm,
            HangingFruitTree,
            PurpleVegetablePlant,
            MelonPlant,
            BluePalm,
            GabeSFeather,
            SeaCrown,
            OrangePetalsPlant,
            EyesPlant,
            RedGreenTentacle,
            PurpleStalk,
            RedBasketPlant,
            RedBush,
            RedConePlant,
            ShellGrass,
            SpottedLeavesPlant,
            RedRollPlant,
            PurpleBranches,
            SnakeMushroom,
            SeaTreaderPoop,
            GenericJeweledDisk,
            FloatingStone,
            BlueAmoeba,
            RedTipRockThings,
            BlueTipLostRiverPlant,
            BlueLostRiverLilly,
            LargeFloater,
            PiecePlaceholder = 3500,
            JeweledDiskPiece,
            CoralChunk,
            KooshChunk,
            StalkerTooth,
            TreeMushroomPiece,
            BulboTreePiece,
            OrangeMushroomSpore,
            PurpleVasePlantSeed,
            AcidMushroomSpore,
            WhiteMushroomSpore,
            PinkMushroomSpore,
            PurpleRattleSpore,
            HangingFruit,
            PurpleVegetable,
            SmallMelon,
            Melon,
            MelonSeed,
            PurpleBrainCoralPiece,
            SpikePlantSeed,
            BluePalmSeed,
            PurpleFanSeed,
            SmallFanSeed,
            PurpleTentacleSeed,
            JellyPlantSeed,
            GabeSFeatherSeed,
            SeaCrownSeed,
            MembrainTreeSeed,
            PinkFlowerSeed,
            FernPalmSeed,
            OrangePetalsPlantSeed,
            EyesPlantSeed,
            RedGreenTentacleSeed,
            PurpleStalkSeed,
            RedBasketPlantSeed,
            RedBushSeed,
            RedConePlantSeed,
            ShellGrassSeed,
            SpottedLeavesPlantSeed,
            RedRollPlantSeed,
            PurpleBranchesSeed,
            SnakeMushroomSpore,
            EnvironmentPlaceholder = 4000,
            Boulder,
            PurpleBrainCoral,
            HangingStinger,
            SpikePlant,
            BrainCoral,
            CoveTree,
            MonsterSkeleton,
            SeaDragonSkeleton,
            ReaperSkeleton,
            CaveSkeleton,
            HugeSkeleton,
            PrecursorKey_Red = 4200,
            PrecursorKey_Blue,
            PrecursorKey_Orange,
            PrecursorKey_White,
            PrecursorKey_Purple,
            PrecursorKey_PurpleFragment,
            PrecursorKeyTerminal,
            PrecursorTeleporter,
            PrecursorEnergyCore,
            PrecursorIonPowerCell,
            PrecursorIonBattery,
            PrecursorThermalPlant,
            PrecursorWarper,
            PrecursorFishSkeleton,
            PrecursorScanner,
            PrecursorLabCacheContainer1,
            PrecursorLabCacheContainer2,
            PrecursorLabTable,
            PrecursorSeaDragonSkeleton,
            PrecursorSensor,
            PrecursorPrisonArtifact1,
            PrecursorPrisonArtifact2,
            PrecursorPrisonArtifact3,
            PrecursorPrisonArtifact4,
            PrecursorPrisonArtifact5,
            PrecursorPrisonArtifact6,
            PrecursorPrisonArtifact7,
            PrecursorPrisonArtifact8,
            PrecursorPrisonArtifact9,
            PrecursorPrisonArtifact10,
            PrecursorPrisonArtifact11,
            PrecursorPrisonArtifact12,
            PrecursorPipeRoomIncomingPipe,
            PrecursorPipeRoomOutgoingPipe,
            PrecursorPrisonLabEmperorFetus,
            PrecursorPrisonLabEmperorEgg,
            PrecursorPrisonAquariumPipe,
            PrecursorPrisonAquariumFinalTeleporter,
            PrecursorPrisonAquariumIncubatorEggs,
            PrecursorPrisonAquariumIncubator,
            PrecursorSurfacePipe,
            PrecursorPrisonArtifact13,
            PrecursorPrisonIonGenerator,
            PrecursorPrisonOutposts,
            ObservatoryOld = 4250,
            PrecursorLostRiverBrokenAnchor = 4300,
            PrecursorLostRiverLabRays,
            PrecursorLostRiverLabBones,
            PrecursorLostRiverLabEgg,
            PrecursorLostRiverProductionLine,
            PrecursorLostRiverWarperParts,
            FilteredWater = 4500,
            DisinfectedWater,
            CookedPeeper,
            CookedHoleFish,
            CookedGarryFish,
            CookedReginald,
            CookedBladderfish,
            CookedHoverfish,
            CookedSpadefish,
            CookedBoomerang,
            CookedEyeye,
            CookedOculus,
            CookedHoopfish,
            NutrientBlock,
            FirstAidKit,
            StillsuitWater,
            BigFilteredWater,
            CookedSpinefish,
            CookedLavaEyeye,
            CookedLavaBoomerang,
            Snack1,
            Snack2,
            Snack3,
            Coffee,
            CuredPeeper = 4600,
            CuredHoleFish,
            CuredGarryFish,
            CuredReginald,
            CuredBladderfish,
            CuredHoverfish,
            CuredSpadefish,
            CuredBoomerang,
            CuredEyeye,
            CuredOculus,
            CuredHoopfish,
            CuredSpinefish,
            CuredLavaEyeye,
            CuredLavaBoomerang,
            MembraneOld = 5000,
            Unobtanium,
            BaseRoom = 5500,
            BaseHatch,
            BaseWall,
            BaseDoor,
            BaseLadder,
            BaseWindow,
            PowerGeneratorOld,
            UnusedOld,
            BaseCorridor,
            BaseFoundation,
            BaseCorridorI,
            BaseCorridorL,
            BaseCorridorT,
            BaseCorridorX,
            BaseReinforcement,
            BaseBulkhead,
            BaseCorridorGlassI,
            BaseCorridorGlassL,
            BaseObservatory,
            BaseConnector,
            BaseMoonpool,
            BaseCorridorGlass,
            BaseUpgradeConsole,
            BasePlanter,
            BaseFiltrationMachine,
            BaseWaterPark,
            BaseMapRoom,
            MapRoomCamera,
            BaseBioReactor,
            BaseNuclearReactor,
            BasePipeConnector,
            RocketBase = 5900,
            RocketBaseLadder,
            RocketStage1,
            RocketStage2,
            RocketStage3,
            TimeCapsule,
            DioramaHullPlate = 6000,
            MarkiplierHullPlate,
            MuyskermHullPlate,
            LordMinionHullPlate,
            JackSepticEyeHullPlate,
            Poster,
            IGPHullPlate,
            GilathissHullPlate,
            Marki1,
            Marki2,
            JackSepticEye,
            EatMyDiction,
            RadiationLeakPoint = 7000,
            SomethingPlaceholder = 10000,
            Fragment,
            Wreck,
            CountOld,
            Databox
        }
    }
}
